#!/bin/bash
#SBATCH -J Pilon_2
#SBATCH --account ACF-UTK0011
#SBATCH --mem=100gb
#SBATCH --nodes=1
#SBATCH --ntasks=48
#SBATCH --time=24:00:00
#SBATCH --partition=campus
#SBATCH --error=error/pilon2.e%j
#SBATCH --output=log/pilon2.o%j
#SBATCH --qos=campus
#SBATCH --exclusive

eval "$(conda shell.bash hook)"

conda activate /lustre/isaac/scratch/jtorre28/enviro/pilonn/

cd /lustre/isaac/scratch/jtorre28/foxgloves/purged/purged2/

java -Xmx90G -jar /lustre/isaac/scratch/jtorre28/enviro/pilonn/share/pilon-1.24-0/pilon.jar --genome /lustre/isaac/scratch/jtorre28/foxgloves/purged/purged2/polished.fasta --frags /lustre/isaac/scratch/jtorre28/foxgloves/purged/purged2/illumina-polished1.bam --frags /lustre/isaac/scratch/jtorre28/foxgloves/purged/purged2/illumina-polished2.bam --output polished2 --changes

