#!/bin/bash
#SBATCH -J solani
#SBATCH --account ACF-UTK0011
##SBATCH --mem=100gb
#SBATCH --nodes=1
#SBATCH --ntasks=48
#SBATCH --time=24:00:00
#SBATCH --partition=campus-bigmem
#SBATCH --error=error/solani.%j
#SBATCH --output=log/solani.%j
#SBATCH --qos=campus-bigmem
#SBATCH --exclusive

cd /lustre/isaac/scratch/jtorre28/foxgloves

module load canu

canu -p foxglove -d /lustre/isaac/scratch/jtorre28/foxgloves genomeSize=300m utgReAlign=true overlapper=mhap -nanopore /lustre/isaac/scratch/jtorre28/basecalling/A_solani/aulacorthum_nanopore.fastq usegrid=false
